src/task/syncBorrowedShips.ts

Unfortunately, AFAICT there's no way to avoid these errors completely,
as there's no API to determine if a character is on a citadel's ACL
short of just trying to retrieve the citadel info.
So I just have to accept the possibility of getting a 403. When that
happens, I will stop retrieving citadel names for that character.
Hopefully, that will be enough to prevent us from running into ESI's
"no more than 100 errors per minute" limit.

Handle "forbidden" errors from citadel data calls.

---

src/infra/taskrunner/Scheduler.ts

this also fixes the set attributes that weren't properly being set.

fix durations by finishing span in finally

---

schema/017-longertext.js

value too long for type character varying(1000)

make it longer

---

src/db/dao/SrpDao.ts

https://github.com/eve-val/eve-roster/blob/9f9b4e3854f91f8301f3f0d0ca422fc65fdc7554/src/task/syncRoster.ts#L169 for a working example.

upsert preserving existing values

---

src/db/tnex/Tnex.ts

idk how to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

allow upsert to do nothing on conflict

---

src/task-registry/scheduledTasks.ts
src/task/syncCombatStats.ts

https://github.com/zKillboard/zKillboard/wiki/API-(Killmails) says we're no longer allowed to specify a start time.
instead, use activity from previous calendar month as the guide.

each 1st of month, update the kills from past calendar month of activity

---

src/db/dao/CombatStatsDao.ts
src/task-registry/scheduledTasks.ts
src/task/syncCombatStats.ts

only refresh data if we haven't grabbed in current calendar month
also only search characters belonging to current members.

better limit search to active corp members

---

package.json
src/task/syncCorps.ts
src/util/asyncUtil.ts
yarn.lock

https://stackoverflow.com/a/52262024

fetch character corps in parallel 10 at a time.

---

.circleci/config.yml

https://circleci.com/developer/orbs/orb/eddiewebb/queue#usage-single_concurrency_job

serialize circleci deploys

---

tsconfig.json

https://www.typescriptlang.org/tsconfig#incremental

cache typescript partial builds to speed compiles

---

src/task/syncCorps.ts

https://share.getcloudapp.com/X6uep6Xx

HTTP 420 enhance your calm

---

src/data-source/esi/error.ts
src/task/syncCorps.ts

keep the old value instead, we'll pick up new value on next sync.

don't set unknown corp for retriable errors

---

src/infra/build-client/webpack.common.ts

Reverts eve-val/eve-roster#547

Revert "import webpack runtime for login too"

---

.circleci/config.yml
package.json
yarn.lock

bump otel & node engine versions

---

package.json
yarn.lock

update all sentry deps together

---

package.json
yarn.lock

solves dependabot security issue

upgrade jest major

---

.github/workflows/dependabot.yml
.github/workflows/fix-lockfile.yml

See https://github.com/dependabot/dependabot-core/issues/3253#:~:text=the%20Actions%20team.-,How%20do%20I%20fix,the%20two%20workflow%20method%3A,-%23%23%23%20.github%2Fworkflows%2Fdependabot_pr

use two-step process for detecting dependabot changes

---

package.json
src/db/tnex/Tnex.ts
yarn.lock

Adjusts for https://github.com/knex/knex/pull/4471 released with knex v1.0.0 https://github.com/knex/knex/releases/tag/1.0.0

roll forward knex with dict return type from insert

---

.yarnrc.yml

disable pnp again

---

package.json
yarn.lock

https://github.com/eve-val/eve-roster/security/dependabot/17

fix minimist vuln

---

.yarnrc.yml

fixes regression in #1112
see https://github.com/yarnpkg/berry/pull/4252 and https://github.com/yarnpkg/berry/issues/3591#issuecomment-1106505298

disable global cache

---

package.json
yarn.lock

Reverts eve-val/eve-roster#1213

Revert "Bump @types/node from 16.11.41 to 18.0.0"

---

package.json
yarn.lock

Reverts eve-val/eve-roster#1336

Revert "Bump vue-router from 4.1.3 to 4.1.5"

---

package.json
yarn.lock

Reverts eve-val/eve-roster#1352

Revert "Revert "Bump vue-router from 4.1.3 to 4.1.5""

---

env.sample
package.json
src/infra/init/Env.ts
src/infra/init/initMonitoring.ts
src/infra/init/initServer.ts
src/server.ts
yarn.lock

This creates a typesafe container for us to read environment variables from.
Spins off sections of server.ts into their own files.

Use envalid to parse environment variables

---

yarn.lock

https://github.com/eve-val/eve-roster/security/dependabot/28
https://github.com/eve-val/eve-roster/security/dependabot/27
https://github.com/eve-val/eve-roster/security/dependabot/24

yarn set resolution

---

package.json
yarn.lock

This reverts commit f2d64349bf9b116a069070f631b23ff998c6c119.

Revert "Bump axios from 1.1.3 to 1.2.0 (#1470)"

---

package.json
yarn.lock

https://github.com/eve-val/eve-roster/security/dependabot/37

update webpack to address cve

---

package.json
yarn.lock

addresses https://github.com/eve-val/eve-roster/security/dependabot/38

remove unused, unmaintained request dep

---

.yarnrc.yml
yarn.lock

https://github.com/swagger-api/apidom/issues/2871

update apidom to avoid overrides

---

src/server/infra/init/initMonitoring.ts

Reverts #1830 #1831 #1832 #1834

open-telemetry/opentelemetry-js/issues/3976

---

src/server/domain/account/accountGroups.ts

Reverts eve-val/eve-roster#1888

Revert "add account group sync telemetry"

---

src/server/domain/sso/loginParams.ts

We maybe want implants, don't care about calendar

Further adjust scopes

---

src/server/data-source/accessToken/jwt.ts

update jwt issuer to include schema version

---

yarn.lock

Fixes https://github.com/eve-val/eve-roster/security/dependabot/52

force axios past 1.4

---

yarn.lock

Fixes https://github.com/eve-val/eve-roster/security/dependabot/55

address npm/ip package vuln

---

src/client/admin/JobDetail.vue

"Now you have two problems" etc.

Make JobDetail regex more permissive

---

package.json
src/server/data-source/esi/EsiEntity.ts
src/server/domain/account/accountGroups.ts
src/server/task/syncRoster.ts
src/server/util/error.ts

Removes some superfluous logs and adds a final summary rollup at the end.

Clean up syncRoster logging

---

src/client/admin/JobDetail.vue
src/client/dashboard/ReauthenticationPrompt.vue
src/server/data-source/accessToken/AccessTokenLoader.ts

- Don't strip whitespace from log lines in JobDetail
- Log when access tokens will expire
- Improve legibility of re-auth bother banner on dashboard

Fix JobDetail rendering, other improvements

---

src/server/util/collection/PriorityQueue.ts
test/server/util/collection/PriorityQueue.test.ts

Pretty standard implementation using a min binary heap. Used in upcoming commits that rework our SRP sync.

Implement PriorityQueue
