- src/client/home.js
- src/client/shared/AppHeader.vue
- src/client/shared/ajaxer.js
- src/client/ships/AllBorrowedShips.vue
- src/client/ships/ShipTable.vue
- src/client/ships/ShipsBorrowedByMe.vue
- src/client/ships/ShipsWrapper.vue
- src/db/dao/CharacterShipDao.ts
- src/infra/express/express.ts
- src/route/home.ts
Add two pages under "Ships" item in the top navigation bar. One, accessible
to all members, shows all ships borrowed by the characters attached to the
current account. The other, restricted to admins, lists all borrowed
ships for the entire corp.
> Simple UI for borrowed ships.

- src/task-registry/scheduledTasks.ts
otherwise long running maintenance functions such as `syncCorps' may stop us for running for minutes at a time.
> don't contend on shared 'cron' channel

- package.json
- src/server.ts
- yarn.lock
As per https://github.com/open-telemetry/opentelemetry-js/pull/2130 this should work...
> s#grpc#@grpc/grpc-js#

- src/task/syncCombatStats.ts
Fetch 2 characters per minute, so that we don't overwhelm zkillboard.
also fixes month calculation.
> slow down to avoid ratelimits

- .circleci/config.yml
`dokku git:sync --build roster-staging https://github.com/eve-val/eve-roster.git master` will run automatically, as COMMAND is overridden.
> use different form of dokku sync

- src/infra/build-client/webpack.common.ts
removes verbose performance suggestions, module output, and splits into multiple hashed module names that can be cached.
https://v4.webpack.js.org/configuration/optimization/#optimizationsplitchunks etc
> split chunks

- .circleci/config.yml
- package.json
- yarn.lock
as per https://github.com/eve-val/eve-roster/pull/730 terser-webpack-plugin has its own types
> remove @types/terser-webpack; bump node version

- package.json
- yarn.lock
Until https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/237 is solved, we need to roll back imagemin-svgo
Solves these errors that have cropped up the past 2 weeks:
```
WARNING in ./src/client/shared/res/LoadingSpinner-spinner.svg
Module Warning (from ./node_modules/image-minimizer-webpack-plugin/dist/loader.js):
Unknown plugin: imagemin-svgo
Did you forget to install the plugin?
You can install it with:
$ npm install imagemin-svgo --save-dev
$ yarn add imagemin-svgo --dev
@ ./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[1]!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[7].use[0]!./src/client/shared/LoadingSpinner.vue?vue&type=template&id=440c8cdd&scoped=true 2:0-57 27:21-31
@ …
```
> revert imagemin-svgo to 9.0.0

- package.json
Reverts eve-val/eve-roster#930
> Revert "cache yarn/cache, not node_modules"

- src/infra/init/Env.ts
It looks like our current environment does not use DOKKU_NGINX_PORT or DOKKU_NGINX_SSL_PORT, but the server is actually designed to function correctly even if none of them are set.
> Adjust Dokku port env vars to be optional

- package.json
- yarn.lock
Reverts eve-val/eve-roster#1499
GLIBC_2.33 missing error because we're on 20.04 which ships GLIBC_2.31
> Revert "Bump sqlite3 from 5.1.2 to 5.1.3"

- package.json
- src/infra/init/Env.ts
- src/infra/init/ExampleLegacyEnvReader.ts
- src/infra/init/initMonitoring.ts
- test/infra/init/ExampleLegacyEnvReader.test.ts
- test/infra/init/FakeEnv.ts
- test/test_infra/mockModule.ts
- test/test_infra/wrapModule.ts
In general, we _should_ be explicitly injecting our env vars into the places that they need to go, but a bunch of legacy code is structured such that the plumbing necessary would be onerous.
Adds the getEnvLegacy() method that any module can call to get access to the global env vars. Also adds a fake implementation for tests. Figuring out how to fake out dependencies in Jest was not the most fun.
> Add support for statically-available Env vars

- package.json
- test/infra/init/ExampleLegacyEnvReader.test.ts
- test/test_infra/mockModule.ts
- test/util/collection/ArrayQueue.test.ts
- test/util/sortBy.test.ts
- test/util/time.test.ts
- yarn.lock
Previously we were using @types/jest to make the jest methods available in tests, but this also made them available...everywhere, including non-test code. This moves to jest's new system where the core jest functions are manually imported.
> Migrate to importing jest globals in tests

- package.json
this all goes away when https://github.com/yarnpkg/berry/pull/5362 merges upstream.
> use postinstall instead of hijacking build-server

- .eslintrc.json
- package.json
- src/bin/witness/RotatingFileLogWriter.ts
- src/infra/build-client/webpack.ts
- src/infra/express/EndpointContext.ts
- src/infra/express/express.ts
- src/infra/express/protectedEndpoint.ts
- src/infra/express/puggle.ts
- src/infra/init/Env.ts
- test/infra/init/FakeEnv.ts
- yarn.lock
When we moved to using HtmlWebpackPlugin to build our pug/HTML templates, it broke our ability to serve those files when in dev mode. Because those files were now compiled by webpack, it meant they no longer existed while in dev mode (all webpack build artifacts are stored in an in-memory file system to increase performance). Express can't see those in-memory files, so it throws errors when you try to navigate to those pages.
The solution is, unfortunately, to completely bypass express's templating system and write our own, wrapping the pug system. Our system can conditionally read from the memory FS, allowing things to work properly both when in dev and prod modes.
Also introduces a new dev env flag, CLIENT_DEV_MODE that allows devs to disable client dev mode (presumably if you're just …
> Get client dev mode working again

- src/client/admin/AccountLog.vue
- src/client/dashboard/OwnedCharacterSlab.vue
- src/client/dev/DevPreview.vue
- src/client/dev/DevToolTip.vue
- src/client/roster/CharacterRow.vue
- src/client/shared/LoadingSpinner.vue
- src/client/shared/ToolTip.vue
- src/client/shared/types.ts
- src/client/srp/battles/BattleRow.vue
- Rewrote most of ToolTip.vue component. Its approach was overly verbose and broke Chrome rendering somehow.
- Reworked ToolTip gravity API to use "primary + secondary" instead of "horizontal + vertical". The previous was difficult to remember and allowed for a nonsensical state ("center center"). The primary gravity option will work for most uses cases ("left"/"top"/"right"/"bottom") and can be optionally augmented with a secondary alignment ("start"/"center"/"end").
- Added a dev page for ToolTip
- Fixed a few other typing errors in related code.
> Fix rendering of ToolTip component

- .eslintrc.json
- src/domain/account/canDesignateMain.ts
We were originally restricting this to a 7-day-from-account-creation window as a security measure, but the security concerns never really came to fruition.
> Allow members to set their mains with no restriction

- src/server/eve/sde.ts
- src/server/eve/sde/loadSdeSkillDefinitions.ts
- src/server/task-registry/runnableTasks.ts
- src/server/task/updateSde/ingestSde.ts
- src/server/task/updateSde/verifyImport.ts
- src/server/task/updateSdeDryRun.ts
- src/server/util/error.ts
Some newer skills have malformed skill requirements, which was causing the import to be rejected. Sigh. The system is already resilient to such problems, but added a way for us to allowlist known discrepancies.
Also added a special "dry run" version of the Update SDE task that is only available on dev builds. Instead of downloading the SDE from the web, it looks for it in tmp/ and doesn't actually commit any changes to the db. Useful when you're trying to figure out why the import is failing.
> Fix "Update SDE" task

- src/client/dashboard/PendingTransferSlab.vue
- src/client/roster/CharacterRow.vue
- src/client/shared/LoadingSpinner.vue
- src/client/shared/ToolTip.vue
- src/client/shared/ToolTipGravity.ts
- src/client/shared/enumProp.ts
- src/shared/util/enum.ts
Creates special handling for string enums as Vue properties. Also adjusts how tooltip renders its contents by default (defaults to inline now, rather than block).
The string enum solution is not ideal, but it's the best option right now until Typescript adds some extra type features for enums.
> Fix up typings of LoadingSpinner and ToolTip

- src/server/route/authenticate.ts
to let hoshi log in after transferring eve accounts, needed to allow unsetting the owner id from ESI and re-setting it later.
> add workaround for hoshi

- src/server/db/dao/ConfigDao.ts
- src/server/task/syncKillmails.ts
This is a temporary hotfix that disables syncing SRP for affiliate corporations until we have a better UI that allows admins to select SRP status on a per-corporation basis.
> Hotfix: only sync SRP for "full" member corporations

- src/server/data-source/accessToken/TokenRefresher.ts
When using a refresh token to refresh an access token fails with an Unauthorized error code, we store an empty refresh token and indicate that the owner of the character needs to re-auth that character so we can get a fresh one. The problem is, we didn't check to see if the refresh token we were trying to refresh with was already empty, so any further API request results in us trying to refresh an access token with an empty refresh token, which is obviously not going to work.
This fix makes refreshAccessToken() fail fast if it's provided with an empty and thus invalid refresh token, instead of trying to hit CCP's endpoints with it.
> Fail fast on empty refresh token

- src/server/task/syncSkills.ts
We expect not to be able to sync skills for characters missing access tokens; they are not a warning.
> Only warn() for ESI errors in syncSkills

- src/server/task/syncBorrowedShips.ts
- src/server/task/syncNotifications.ts
ESI errors should be warnings but access token errors should not be.
> Don't warn for AccessTokenErrors

- src/server/task/syncBorrowedShips.ts
- src/server/task/syncNotifications.ts
A 403 response implies that the token is either invalid or does not have the scope we're expecting; in either case, we should require a new login to get an updated token.
> Expire tokens that result in 403 responses

- src/server/task/syncBorrowedShips.ts
This is info-level because it does not necessarily constitute a problem; we expect sometimes ships will wind up in structures to which someone doesn't have access and thus cannot resolve the name via API.
> Being unable to access a structure is expected sometimes

- src/server/db/dao/AccessTokenDao.ts
- src/server/task/syncBorrowedShips.ts
- src/server/task/syncNotifications.ts
Unlike 401 errors which imply we need to refresh the access token, 403 errors imply our current token doesn't allow us to read something we expected to, so we should stop trying and require a fresh authentication for that character before trying again.
> Mark refresh tokens invalid for 403s on expected scopes

- src/server/task/syncBorrowedShips.ts
There's nothing we can particularly do to fix 5xx errors, so this makes us not count increment the failure count for borrowed ship syncing if we run into one, so the job won't show up as 'partial' success just because of a CCP-side issue.
> Don't count 5xx errors for sync failures

- src/server/infra/init/initMonitoring.ts
```
[witness] Spawning child "/app/out/server/server.js"...
[witness] Base logs path: /logs
[witness] Opening log file /logs/roster_logs_2023-07-19.txt
2023-07-19T22:23:01.529Z   225 U file:///app/out/server/infra/init/initMonitoring.js:8
[witness] Child exited w/ code 1 and signal null
2023-07-19T22:23:01.570Z   225 U import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-grpc";
2023-07-19T22:23:01.580Z   225 U          ^^^^^^^^^^^^^^^^^
2023-07-19T22:23:01.581Z   225 U SyntaxError: Named export 'OTLPTraceExporter' not found. The requested module '@opentelemetry/exporter-trace-otlp-grpc' is a CommonJS module, which may not support all module.exports as named exports.
2023-07-19T22:23:01.582Z   225 U CommonJS modules can always be imported via the default export, for …
```
> cjs workaround?

- src/client/shared/EveImage.vue
- src/client/shared/types.ts
- src/client/srp/SrpTriplet.vue
- src/client/srp/battles/BattleRow.vue
- src/server/domain/battle/battlesToJson.ts
- src/shared/route/api/srp/battle/battle_GET.ts
- src/shared/util/DefaultMap.ts
When displaying battle reports, cluster killmails from the same alliance into one row. Previously we clustered by corporation, which led to visual noise.
Member corps are still pulled out into their own lines.
> Cluster battle reports by alliance (rather than corp)

- src/client/roster/CharacterRow.vue
Errors for non-main characters will only result in a warning indicator when viewing the top level list (but will be visible as errors when the main's row is expanded.
> Focus on main character errors in overall list

- src/client/roster/CharacterRow.vue
Reverts eve-val/eve-roster#2056. Turns out this code branch is actually dead and the max is calculated via the aggregate character functionality in RosterList.vue
> Revert "Focus on main character errors in overall list"

- src/server/task/syncKillmails/process/KillmailProcessor.ts
avoids crash inside KM processing if all KMs returned are already present & do not need modification
observability plan: https://ui.honeycomb.io/of-sound-mind/datasets/roster-production/result/qT7KKqNwSfy should start showing successes again.
> fix: check if updateRows length > 0

- src/server/route/api/admin/tasks/job_GET.ts
Previously, final elements could get get off if they all shared the same timestamp.
> Fix minor log display bug

- src/server/data-source/esi/error.ts
- src/server/data-source/esi/names.ts
- src/server/infra/logging/WitnessLogger.ts
- src/server/infra/taskrunner/Scheduler.ts
- src/server/task/syncCombatStats.ts
- src/server/task/syncRoster.ts
- src/server/task/updateSde/ingestSde.ts
- src/server/util/error.ts
Centralizes our error-to-string pipelines into just two methods:
- errorMessage(e: unknown)
- stackTrace(e: unknown)
Both methods have specialized handling for VError, AxiosError, nested Errors, and non-error objects.
Updates many call sites to use the proper method (many, including the job scheduler, were just doing the Wrong Thing).
> Clean up a lot of error logging

- src/server/data-source/accessToken/AccessTokenLoader.ts
- src/server/db/tnex/Tnex.ts
- src/server/db/tnex/TnexBuilder.ts
- test/test_infra/db/FakeDb.ts
Previously if the first DB object it was passed was a transaction, bad things would happen
> Change AccessTokenLoader to always use root DB connection

- src/server/data-source/accessToken/accessToken.ts
- src/server/data-source/accessToken/runAsDirector.ts
- src/server/data-source/esi/EsiEntity.ts
- src/server/db/dao/RosterDao.ts
- src/server/task/syncRoster.ts
- src/server/util/Result.ts
Intruduces runAsDirector(), a new method that allows jobs to safely attempt to run a task using an arbitary corporation director's access tokens. Supports retrying across multiple directors for multiply-redundant behavior.
> Convert syncRoster to use runAsDirector()

- src/server/util/error.ts
- src/server/util/flow/flow.ts
- test/server/util/flow/flow-batch.test.ts
- test/server/util/flow/flow-core.test.ts
- test/server/util/flow/flow-mapParallel.test.ts
- test/server/util/flow/flow-once.test.ts
- test/server/util/flow/flow-parallel.test.ts
- test/server/util/flow/flow-source-node.test.ts
- test/server/util/flow/flow-transform.test.ts
- test/server/util/flow/flow-util.ts
Implements the `flow` microlibrary, a small system for managing asynchronous pipeline processing. This is largely a replacement for using Node Streams in object mode, which were never meant for this purpose and don't feel great to use in this form.
We should really juse use RxJS instead of this library, but I'm stubborn and I don't like the shape of its APIs. The structure of this version is largely inspired by Kotlin flows.
The system supports full backpressure control, so large sources like files or database queries will not consume excessive memory.
> Introduce flows

- src/server/data-source/esi/endpoints.ts
- src/server/data-source/esi/market/fetchAverageMarketPrices.ts
- src/server/data-source/esi/market/fetchJitaSellPrices.ts
- src/server/data-source/esi/market/fetchMarketStats.ts
- src/server/domain/srp/triage/payout.ts
Previously we were using fetchJitaSellPrices, which we still maintain, but honestly we should probably just use the galactic average, which CCP provides a very efficient and convenient endpoint for.
Adds fetchAverageMarketPrices, which does just that. It caches and coalesces requests and is just generally quite fast. It stores all ~15k market prices in memory, but that's probably fine.
> Implement fetchAverageMarketPrices

- src/client/srp/AdaptiveLink.vue
- src/client/srp/SrpTriplet.vue
TL;DR, don't set default: "" for optional string properties.
> Fix bug where SrpTriplets weren't rendering hrefs properly
